"use client";

import { useEffect, useState } from "react";

/* ─────────────────────────────────────────────
   JSON-LD Structured Data
───────────────────────────────────────────── */
const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Kenric Company",
  url: "https://ramon.kenriccompany.com",
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+1-442-269-1546",
    contactType: "customer support",
    email: "ramon@kenriccompany.com",
  },
  address: {
    "@type": "PostalAddress",
    streetAddress: "1100 Melody Lane STE 118",
    addressLocality: "Roseville",
    addressRegion: "CA",
    addressCountry: "US",
  },
};

const productSchema = {
  "@context": "https://schema.org",
  "@type": "Product",
  name: "13-Week Dynamic Cash Flow Forecasting Model",
  description:
    "A comprehensive, automated treasury management Excel workbook engineered for multi-channel e-commerce and retail operations. Features automated liquidity tracking, multi-channel inflow logic, granular outflow mapping, and built-in variance & historical snapshot tabs.",
  brand: {
    "@type": "Brand",
    name: "Kenric Company",
  },
  offers: {
    "@type": "Offer",
    priceCurrency: "USD",
    price: "150.00",
    availability: "https://schema.org/InStock",
    itemCondition: "https://schema.org/NewCondition",
  },
  image: "https://ramon.kenriccompany.com/13-week-cashflow-product-box.png",
};

/* ─────────────────────────────────────────────
   Nav / footer brand: Ramon Puente by Kenric Company
───────────────────────────────────────────── */
function BrandMark({ variant = "nav" }: { variant?: "nav" | "footer" }) {
  const isNav = variant === "nav";

  return (
    <p className="leading-tight">
      <span
        className={
          isNav
            ? "text-white font-bold text-sm lg:text-base tracking-tight"
            : "text-white font-bold text-xl tracking-tight"
        }
      >
        Ramon Puente
      </span>
      <span
        className={
          isNav
            ? "text-slate-400 font-extralight text-[0.65rem] sm:text-xs lg:text-sm tracking-wide"
            : "text-slate-500 font-extralight text-xs sm:text-sm tracking-wide"
        }
      >
        {" "}
        by Kenric Company
      </span>
    </p>
  );
}

/* ─────────────────────────────────────────────
   Policy modal content
───────────────────────────────────────────── */
type PolicyKey = "tos" | "refund" | "privacy";

const policyContent: Record<PolicyKey, { title: string; body: React.ReactNode }> = {
  tos: {
    title: "Terms of Service",
    body: (
      <div className="space-y-4 text-sm text-slate-600 leading-relaxed">
        <p>
          <strong>Effective Date:</strong> June 2025 &nbsp;|&nbsp;{" "}
          <strong>Entity:</strong> Ramon R Puente Jr | Kenric Company
        </p>
        <h3 className="font-semibold text-slate-800 text-base">1. Digital Product Delivery</h3>
        <p>
          All products are delivered 100% digitally via email download links immediately following
          checkout confirmation. Customers must provide a valid email address at checkout to receive
          their purchase.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">2. Intellectual Property</h3>
        <p>
          All digital assets, templates, and workbooks sold on this site are the exclusive
          intellectual property of Kenric Company. Purchasers are granted a single-user,
          non-transferable license for internal business use only. Redistribution, resale, or
          public sharing is strictly prohibited.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">3. Acceptable Use</h3>
        <p>
          Products may be used for legitimate internal business, financial planning, and operational
          purposes only. Any attempt to reverse-engineer, decompile, or repurpose the underlying
          models for competing commercial products is prohibited.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">4. Limitation of Liability</h3>
        <p>
          Kenric Company provides financial modeling tools for informational and operational
          planning purposes. These tools do not constitute financial, legal, or investment advice.
          Kenric Company shall not be liable for any business decisions made based on outputs
          generated by these templates.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">5. Governing Law</h3>
        <p>
          These Terms are governed by the laws of the State of California. Any disputes shall be
          resolved in the courts of Placer County, California.
        </p>
      </div>
    ),
  },
  refund: {
    title: "Refund Policy",
    body: (
      <div className="space-y-4 text-sm text-slate-600 leading-relaxed">
        <h3 className="font-semibold text-slate-800 text-base">No-Refund Policy on Digital Downloads</h3>
        <p>
          Due to the irrecoverable nature of digital downloads, all sales of Excel workbooks and
          templates are final. Support is provided for technical setup issues.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Technical Support</h3>
        <p>
          If you experience any technical difficulties accessing or using your purchased template,
          please contact our support team at{" "}
          <a href="mailto:ramon@kenriccompany.com" className="text-blue-600 underline">
            ramon@kenriccompany.com
          </a>{" "}
          within 30 days of purchase. We are committed to ensuring your product functions as
          described.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Exceptions</h3>
        <p>
          In the rare event that a file is determined to be corrupted or fundamentally different
          from the product description, Kenric Company reserves the right to issue a replacement
          file or store credit at our sole discretion.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Chargebacks</h3>
        <p>
          Initiating a chargeback without first contacting support will result in permanent ban
          from future purchases. All chargeback claims will be disputed with full transaction
          evidence including delivery confirmation.
        </p>
      </div>
    ),
  },
  privacy: {
    title: "Privacy Policy",
    body: (
      <div className="space-y-4 text-sm text-slate-600 leading-relaxed">
        <p>
          <strong>Effective Date:</strong> June 2025 &nbsp;|&nbsp;{" "}
          <strong>Entity:</strong> Ramon R Puente Jr | Kenric Company
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Information We Collect</h3>
        <p>
          When you complete a purchase, our payment processor (Stripe) collects your name, email
          address, and payment details. Kenric Company does not store or have direct access to
          full payment card numbers. We may retain your name and email for order fulfillment and
          support purposes only.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">How We Use Your Information</h3>
        <p>
          Your information is used solely to fulfill your order (delivering the digital download
          link), respond to support inquiries, and send transactional communications related to
          your purchase.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Third-Party Processors</h3>
        <p>
          Checkout is handled securely via Stripe, Inc. Stripe&apos;s privacy policy governs the
          handling of your payment data. We do not sell, rent, or share your personal information
          with any third parties for marketing purposes.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Data Security</h3>
        <p>
          All checkout transactions are encrypted via TLS/SSL. We follow industry-standard
          practices to protect the security and integrity of customer data.
        </p>
        <h3 className="font-semibold text-slate-800 text-base">Contact</h3>
        <p>
          For any privacy-related questions, contact us at{" "}
          <a href="mailto:ramon@kenriccompany.com" className="text-blue-600 underline">
            ramon@kenriccompany.com
          </a>
          .
        </p>
      </div>
    ),
  },
};

/* ─────────────────────────────────────────────
   Policy Modal Component
───────────────────────────────────────────── */
function PolicyModal({
  policyKey,
  onClose,
}: {
  policyKey: PolicyKey;
  onClose: () => void;
}) {
  const { title, body } = policyContent[policyKey];

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handleKey);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", handleKey);
      document.body.style.overflow = "";
    };
  }, [onClose]);

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-title"
    >
      <div
        className="absolute inset-0 bg-navy-950/70 backdrop-blur-sm"
        onClick={onClose}
        aria-hidden="true"
      />
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h2 id="modal-title" className="text-xl font-bold text-slate-900">
            {title}
          </h2>
          <button
            onClick={onClose}
            className="p-2 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
            aria-label="Close modal"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div className="overflow-y-auto px-6 py-5">{body}</div>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────────
   Navbar
───────────────────────────────────────────── */
function Navbar({ onPolicyOpen }: { onPolicyOpen: (k: PolicyKey) => void }) {
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const navLinks = [
    { href: "#services", label: "Services" },
    { href: "#products", label: "Products" },
    { href: "#contact", label: "Contact" },
  ];

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        scrolled
          ? "bg-navy-950/90 backdrop-blur-md shadow-lg border-b border-white/10"
          : "bg-transparent"
      }`}
    >
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" aria-label="Main navigation">
        <div className="flex items-center justify-between h-16 lg:h-20">
          {/* Logo */}
          <a
            href="#"
            className="hover:opacity-90 transition-opacity"
            aria-label="Ramon Puente by Kenric Company home"
          >
            <BrandMark variant="nav" />
          </a>

          {/* Desktop nav */}
          <div className="hidden md:flex items-center gap-8">
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="text-slate-300 hover:text-white font-medium text-sm tracking-wide transition-colors duration-150"
              >
                {link.label}
              </a>
            ))}
            <a
              href="#products"
              className="btn-primary text-sm px-5 py-2.5"
            >
              Browse Models
            </a>
          </div>

          {/* Mobile hamburger */}
          <button
            className="md:hidden p-2 rounded-lg text-slate-300 hover:text-white hover:bg-white/10 transition-colors"
            onClick={() => setMobileOpen(!mobileOpen)}
            aria-expanded={mobileOpen}
            aria-label="Toggle navigation menu"
          >
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              {mobileOpen ? (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              ) : (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              )}
            </svg>
          </button>
        </div>

        {/* Mobile menu */}
        {mobileOpen && (
          <div className="md:hidden py-4 border-t border-white/10 space-y-2">
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="block px-4 py-2 text-slate-300 hover:text-white hover:bg-white/10 rounded-lg font-medium text-sm transition-colors"
                onClick={() => setMobileOpen(false)}
              >
                {link.label}
              </a>
            ))}
            <div className="pt-2 px-4">
              <a href="#products" className="btn-primary w-full text-sm justify-center" onClick={() => setMobileOpen(false)}>
                Browse Models
              </a>
            </div>
          </div>
        )}
      </nav>
    </header>
  );
}

/* ─────────────────────────────────────────────
   Hero Section
───────────────────────────────────────────── */
function HeroSection() {
  return (
    <section
      id="services"
      className="relative min-h-screen flex items-center bg-gradient-to-br from-navy-950 via-navy-800 to-navy-700 overflow-hidden"
      aria-label="Services hero"
    >
      {/* Background grid pattern */}
      <div
        className="absolute inset-0 opacity-[0.04]"
        style={{
          backgroundImage:
            "linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)",
          backgroundSize: "60px 60px",
        }}
        aria-hidden="true"
      />
      {/* Radial glow */}
      <div
        className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-600/20 rounded-full blur-3xl pointer-events-none"
        aria-hidden="true"
      />
      <div
        className="absolute bottom-1/4 right-1/4 w-64 h-64 bg-blue-400/10 rounded-full blur-3xl pointer-events-none"
        aria-hidden="true"
      />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 lg:py-32 w-full">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: Copy */}
          <div className="space-y-8">
            <div>
              <span className="section-label">Financial Engineering & Advisory</span>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white leading-tight tracking-tight">
                Advanced Financial{" "}
                <span className="text-blue-400">Modeling</span> &amp; Data{" "}
                <span className="text-blue-400">Architecture</span>
              </h1>
            </div>
            <p className="text-lg sm:text-xl text-slate-300 leading-relaxed max-w-xl">
              Engineering institutional-grade treasury frameworks, automated forecasting workbooks,
              and data blueprints designed to maximize cash flow transparency and scale operational
              efficiency.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <a href="#products" className="btn-enterprise">
                Explore Forecasting Models
                <svg
                  className="ml-2 w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M13 7l5 5m0 0l-5 5m5-5H6"
                  />
                </svg>
              </a>
              <a
                href="#contact"
                className="inline-flex items-center justify-center px-6 py-3 rounded-lg font-semibold text-white border border-white/30 hover:border-white/60 hover:bg-white/10 transition-all duration-200"
              >
                Schedule a Consultation
              </a>
            </div>

            {/* Credibility chips */}
            <div className="flex flex-wrap gap-3 pt-2">
              {[
                "Treasury Management",
                "Cash Flow Forecasting",
                "Data Architecture",
                "E-commerce Analytics",
              ].map((chip) => (
                <span
                  key={chip}
                  className="px-3 py-1 rounded-full text-xs font-medium bg-white/10 text-slate-300 border border-white/20"
                >
                  {chip}
                </span>
              ))}
            </div>
          </div>

          {/* Right: Hero image */}
          <div className="relative hidden lg:block">
            <div className="relative rounded-2xl overflow-hidden shadow-2xl border border-white/10">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80"
                alt="Corporate financial data analytics dashboard showing cash flow forecasting models"
                width={800}
                height={560}
                className="w-full h-auto object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-navy-950/60 to-transparent" aria-hidden="true" />
            </div>
            {/* Floating stat cards */}
            <div className="absolute -bottom-6 -left-6 bg-white rounded-xl shadow-xl p-4 border border-slate-100">
              <p className="text-xs text-slate-500 font-medium uppercase tracking-wide">Forecast Accuracy</p>
              <p className="text-2xl font-bold text-navy-950 mt-1">98.4%</p>
            </div>
            <div className="absolute -top-6 -right-6 bg-navy-800 rounded-xl shadow-xl p-4 border border-white/10">
              <p className="text-xs text-slate-400 font-medium uppercase tracking-wide">Avg. Time Saved</p>
              <p className="text-2xl font-bold text-white mt-1">14 hrs/wk</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────
   Product Image (with Unsplash fallback)
───────────────────────────────────────────── */
function ProductImage() {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/13-week-cashflow-product-box.png"
      alt="13-Week Dynamic Cash Flow Forecasting Model Box Art"
      width={480}
      height={360}
      className="w-full h-auto rounded-xl shadow-2xl"
    />
  );
}

/* ─────────────────────────────────────────────
   Products Section
───────────────────────────────────────────── */
function ProductsSection() {
  return (
    <section
      id="products"
      className="py-20 lg:py-32 bg-white"
      aria-label="Digital product showcase"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <span className="section-label">Digital Asset Vault</span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-navy-950 leading-tight">
            Premium Financial Modeling Toolkits
          </h2>
          <p className="mt-4 text-lg text-slate-500 leading-relaxed">
            Institutional-grade Excel workbooks engineered for precision. Deploy immediately —
            no configuration required.
          </p>
        </div>

        {/* Product card */}
        <div className="bg-slate-50 rounded-3xl border border-slate-200 overflow-hidden shadow-lg max-w-5xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-0">
            {/* Left: Product image */}
            <div className="relative bg-navy-950 flex items-center justify-center p-8 lg:p-12 min-h-[320px]">
              <div className="relative w-full max-w-sm mx-auto">
                <ProductImage />
              </div>
              {/* Badge */}
              <div className="absolute top-4 right-4 bg-blue-600 text-white text-xs font-bold px-3 py-1.5 rounded-full uppercase tracking-wider shadow">
                Instant Download
              </div>
            </div>

            {/* Right: Product details */}
            <div className="p-8 lg:p-12 flex flex-col justify-between">
              <div className="space-y-6">
                <div>
                  <span className="text-blue-600 text-xs font-bold uppercase tracking-widest">Excel Workbook Template</span>
                  <h3 className="mt-2 text-2xl lg:text-3xl font-extrabold text-navy-950 leading-tight">
                    13-Week Dynamic Cash Flow Forecasting Model
                  </h3>
                </div>

                {/* Price */}
                <div className="flex items-baseline gap-2">
                  <span className="text-4xl font-black text-navy-950">$150.00</span>
                  <span className="text-slate-500 font-medium">USD</span>
                </div>

                {/* Description */}
                <div className="space-y-3">
                  <p className="text-slate-600 leading-relaxed">
                    A comprehensive, automated treasury management Excel workbook engineered for
                    multi-channel e-commerce and retail operations.
                  </p>
                  <div>
                    <h4 className="font-bold text-navy-950 text-sm uppercase tracking-wide mb-2">
                      Core Features
                    </h4>
                    <ul className="space-y-2">
                      {[
                        "Automated liquidity, headroom & runway tracking",
                        "Multi-channel inflow logic (Shopify, Amazon, Sprouts)",
                        "Granular outflow mapping & Line of Credit (LOC) calculators",
                        "Built-in variance & historical snapshot tabs",
                      ].map((feature) => (
                        <li key={feature} className="flex items-start gap-2 text-slate-600 text-sm">
                          <svg
                            className="w-4 h-4 text-blue-500 mt-0.5 shrink-0"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            aria-hidden="true"
                          >
                            <path
                              fillRule="evenodd"
                              d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          {feature}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Delivery note */}
                <p className="text-xs text-slate-400 italic border-t border-slate-200 pt-4">
                  Delivered instantly via secure digital download (.xlsx). No physical product
                  included.
                </p>
              </div>

              {/* CTA */}
              <div className="mt-8">
                <a
                  href="https://buy.stripe.com/9B6aEXgAG65v5O77E7eME01"
                  className="btn-enterprise w-full"
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label="Purchase 13-Week Dynamic Cash Flow Forecasting Model for $150.00 USD"
                >
                  Purchase Template — $150.00
                  <svg
                    className="ml-2 w-5 h-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M17 8l4 4m0 0l-4 4m4-4H3"
                    />
                  </svg>
                </a>
                <p className="text-center text-xs text-slate-400 mt-3">
                  Secure checkout via Stripe &nbsp;·&nbsp; Instant delivery to your inbox
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────
   Contact Section
───────────────────────────────────────────── */
function ContactSection() {
  return (
    <section
      id="contact"
      className="py-20 lg:py-28 bg-slate-50 border-t border-slate-200"
      aria-label="Contact and consultation"
    >
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <span className="section-label">Get in Touch</span>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-navy-950 leading-tight">
          Advisory & Support Inquiries
        </h2>
        <p className="mt-4 text-lg text-slate-500 max-w-xl mx-auto leading-relaxed">
          Reach out directly for enterprise consulting engagements, custom modeling projects, or
          post-purchase technical support.
        </p>

        <div className="mt-12 grid sm:grid-cols-2 gap-6 max-w-xl mx-auto">
          {/* Email */}
          <a
            href="mailto:ramon@kenriccompany.com"
            className="group flex items-center gap-4 p-6 bg-white rounded-2xl border border-slate-200 shadow-sm hover:shadow-md hover:border-blue-200 transition-all duration-200"
            aria-label="Send email to ramon@kenriccompany.com"
          >
            <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center group-hover:bg-blue-100 transition-colors">
              <svg
                className="w-6 h-6 text-blue-600"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
            </div>
            <div className="text-left">
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">Email Support</p>
              <p className="text-sm font-semibold text-navy-950 group-hover:text-blue-600 transition-colors break-all">
                ramon@kenriccompany.com
              </p>
            </div>
          </a>

          {/* Phone */}
          <a
            href="tel:+14422691546"
            className="group flex items-center gap-4 p-6 bg-white rounded-2xl border border-slate-200 shadow-sm hover:shadow-md hover:border-blue-200 transition-all duration-200"
            aria-label="Call +1 (442) 269-1546"
          >
            <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center group-hover:bg-blue-100 transition-colors">
              <svg
                className="w-6 h-6 text-blue-600"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.948V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                />
              </svg>
            </div>
            <div className="text-left">
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">Phone Support</p>
              <p className="text-sm font-semibold text-navy-950 group-hover:text-blue-600 transition-colors">
                +1 (442) 269-1546
              </p>
            </div>
          </a>
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────
   Footer
───────────────────────────────────────────── */
function Footer({ onPolicyOpen }: { onPolicyOpen: (k: PolicyKey) => void }) {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-navy-950 text-slate-400" aria-label="Site footer">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16">
        <div className="grid md:grid-cols-3 gap-10 pb-10 border-b border-white/10">
          {/* Brand col */}
          <div>
            <div className="mb-3">
              <BrandMark variant="footer" />
            </div>
            <p className="text-sm leading-relaxed text-slate-400 max-w-xs">
              Premium financial modeling tools and management consulting frameworks engineered for
              institutional-grade outcomes.
            </p>
          </div>

          {/* Navigation col */}
          <div>
            <h6 className="text-white font-semibold text-sm uppercase tracking-widest mb-4">
              Navigation
            </h6>
            <nav aria-label="Footer navigation">
              <ul className="space-y-2 text-sm">
                {[
                  { href: "#services", label: "Services" },
                  { href: "#products", label: "Products" },
                  { href: "#contact", label: "Contact" },
                ].map((link) => (
                  <li key={link.href}>
                    <a
                      href={link.href}
                      className="hover:text-white transition-colors"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>

          {/* Legal col */}
          <div>
            <h6 className="text-white font-semibold text-sm uppercase tracking-widest mb-4">
              Legal & Compliance
            </h6>
            <ul className="space-y-2 text-sm">
              {(
                [
                  { key: "tos", label: "Terms of Service" },
                  { key: "refund", label: "Refund Policy" },
                  { key: "privacy", label: "Privacy Policy" },
                ] as { key: PolicyKey; label: string }[]
              ).map(({ key, label }) => (
                <li key={key}>
                  <button
                    onClick={() => onPolicyOpen(key)}
                    className="hover:text-white transition-colors text-left underline underline-offset-2 decoration-slate-600 hover:decoration-white"
                  >
                    {label}
                  </button>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Bottom row */}
        <div className="pt-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <p className="text-xs text-slate-500 leading-relaxed">
            <strong className="text-slate-400">Ramon R Puente Jr | Kenric Company</strong>
            <br />
            1100 Melody Lane STE 118, Roseville, CA
          </p>
          <p className="text-xs text-slate-600">
            &copy; {currentYear} Kenric Company. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}

/* ─────────────────────────────────────────────
   Root Page
───────────────────────────────────────────── */
export default function Page() {
  const [activePolicy, setActivePolicy] = useState<PolicyKey | null>(null);

  return (
    <>
      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }}
      />

      <Navbar onPolicyOpen={setActivePolicy} />

      <main>
        <HeroSection />
        <ProductsSection />
        <ContactSection />
      </main>

      <Footer onPolicyOpen={setActivePolicy} />

      {activePolicy && (
        <PolicyModal
          policyKey={activePolicy}
          onClose={() => setActivePolicy(null)}
        />
      )}
    </>
  );
}
